# Generated by Django 5.0.6 on 2024-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='daily_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
