# Generated by Django 5.0.6 on 2024-07-07 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='scale',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
