# Generated by Django 5.0.6 on 2024-07-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last_claim', models.DateTimeField()),
                ('count_last_claim', models.IntegerField(default=0)),
                ('levrage', models.IntegerField(default=1)),
                ('amount_tank', models.IntegerField(default=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click_account', to='authentication.customuser')),
            ],
            options={
                'verbose_name': 'AccountUser',
                'verbose_name_plural': 'AccountUsers',
            },
        ),
    ]
