# Generated by Django 5.0.6 on 2024-07-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_customuser_strike'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='images/diamond_thumbnail/')),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('discount_per_percent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('amount', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.diamondpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.customuser')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.wallet')),
            ],
        ),
    ]
