# Generated by Django 5.0.6 on 2024-07-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_to_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diamondpackage',
            old_name='discount_per_percent',
            new_name='discount',
        ),
    ]
