# Generated by Django 5.0.6 on 2024-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_discount_per_percent_diamondpackage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamondpackage',
            name='price',
            field=models.FloatField(),
        ),
    ]
