# Generated by Django 5.0.6 on 2024-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_diamondpackage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamondpackage',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
