# Generated by Django 5.0.6 on 2024-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_diamondpackage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
