# Generated by Django 5.0.6 on 2024-07-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_tx_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondpackage',
            name='short_description',
        ),
    ]
