# Generated by Django 5.0.6 on 2024-07-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_diamondpackage_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to_wallet',
        ),
    ]
