# Generated by Django 5.0.6 on 2024-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_url',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
