# Generated by Django 5.0.6 on 2024-07-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_cover_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_key', to='authentication.customuser')),
            ],
            options={
                'verbose_name': 'Forgot Key',
                'verbose_name_plural': 'Forgot Keys',
            },
        ),
    ]
