# Generated by Django 5.0.6 on 2024-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_forgotkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotkey',
            name='last_send_sms',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
