# Generated by Django 5.0.6 on 2024-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_forgotkey_last_send_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotkey',
            name='last_send_sms',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
