# Generated by Django 5.0.6 on 2024-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_news_title_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strike',
            field=models.IntegerField(default=0),
        ),
    ]
