# Generated by Django 5.0.6 on 2024-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
