# Generated by Django 5.0.6 on 2024-07-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('point_value', models.IntegerField(default=0)),
                ('image_url', models.ImageField(upload_to='tasks')),
                ('link', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='DailyCompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_claimed_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='authentication.customuser')),
            ],
            options={
                'verbose_name': 'Daily Completed Task',
                'verbose_name_plural': 'Daily Completed Tasks',
            },
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='authentication.customuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_completed', to='task.task')),
            ],
            options={
                'verbose_name': 'Completed Task',
                'verbose_name_plural': 'Completed Tasks',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
